services:
  - type: web
    name: port-plaisance-api
    env: node
    buildCommand: |
      npm run install:prod
      echo "=== Vérification des modèles ==="
      ls -R server/models/
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
    healthCheckPath: /api/health

  - type: static
    name: port-plaisance-client
    env: static
    buildCommand: |
      cd client
      npm install
      npm run build
    staticPublishPath: ./client/dist
    envVars:
      - key: VITE_API_URL
        value: https://port-plaisance-api.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
